### PR TITLE
Update weapons.lua

### PR DESCRIPTION
**Pull request by Demo4889**
Adding weapon_stungun_mp and all durability to weapons as update https://github.com/qbcore-framework/qb-weapons/pull/67 will be looking for it.

### CODE REVIEW

**Comment by Demo4889** [comment]
@evanillaa here's the update you are looking for with the new stun gun, and the new durability you are using in the weapons area.

**Review by darknight2590 — APPROVED** [review]

**Comment by Mojito-Fivem** [comment]
Why is this needed? `weapon_stungun_mp` is identical to `weapon_stungun`?

**Review by evanillaa — APPROVED** [review]

**Comment by evanillaa** [comment]
Thanks for the addition. It will be an option to use for users, to use what they want

**Comment by BerkieBb** [comment]
> Why is this needed? `weapon_stungun_mp` is identical to `weapon_stungun`?

Well rockstar probably meant for the mp version to be used by players and the other meant for npc's, not sure why there's 2 different ones though, rockstar logic not just keeping one

**Comment by darknight2590** [comment]
When accept this I will add 'Recoil' = nil or 'Recoil' = 2
It will be easy to deal with new weapons, Weapons need that

**Comment by FjamZoo** [comment]
There's conflicts and QBCore most likely won't be updated to 2545 due to stability issues atm.

**Comment by IdrisDose** [comment]
Closing due to durability staying in qb-weapons.

**Pull request closed without merging**
