### PR TITLE
Feat. Main Test Command

### PR DESCRIPTION
**Pull request by StuwStuw**
**Describe Pull request**
Implemented test command to main.lua on client side. Allows user to check if commands are working properly. :)

If your PR is to fix an issue mention that issue here.
There was no way for people to test if a command worked on the client side. :)

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Review by uShifty — APPROVED** [review]
Looks good to me 👍

**Comment by Mojito-Fivem** [comment]
All good to merge this into main 👍asap

**Comment by YeahItsHayden** [comment]
Why

**Comment by izMystic** [comment]
Why

**Review by ihyajb — APPROVED** [review]

**Comment by ihyajb** [comment]
10/10

**Pull request closed without merging**
