### PR TITLE
refactor: utilise lib/MySQL

### PR DESCRIPTION
**Pull request by thelindat**
**Describe Pull request**
oxmysql will be encouraging imports over raw export calls. This comes with a few advantages such as performance (faster table lookups), debugging (easier to locate problematic queries) and error catching (invalid arguments, check if resource is started, etc).

v2.0.0 is going to introduce a lot of internal changes and changing some export names to more accurately reflect behaviour - MySQL.lua makes it easy to ensure API compatibility.

Refer to https://github.com/overextended/oxmysql/issues/72

**Questions (please complete the following information):**
- [ ] Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no]
- [x] Does your code fit the style guidelines? [yes/no]
- [x] Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Review by xenfovn — APPROVED** [review]
fast

**Review by xenfovn — CHANGES_REQUESTED** [review]
selectSingle nil

**Comment by thelindat** [comment]
This stuff already exists in oxmysql, and I expect a complete 💩 show from people upgrading oxmysql without having updated exports and fxmanifests to include `@oxmysql/lib/MySQL.lua`.

These changes either need to be made everywhere, or QB can fork oxmysql as-is to continue using the current export names.

Compare [develop](https://github.com/overextended/oxmysql/blob/main/lua/lib/MySQL.lua) branch's MySQL.lua to the [current version](https://github.com/overextended/oxmysql/blob/main/lua/lib/MySQL.lua).

**Comment by thelindat** [comment]
I've pushed several improvements to existing queries which will only work with v1.9.0 None of it's tested so that'll be up to somebody here.

**Comment by BerkieBb** [comment]
Tested the PR, works perfectly

**Comment by thelindat** [comment]
I ended up adding different syntax you can utilise; mysql-async compatible functions (with the exception of fetchSingle/prepare or oxmysql syntax which is a mix between the two. Feel free to implement based on preference.

```
exports.oxmysql:query (previously exports.oxmysql:execute)
MySQL.Async.fetchAll = MySQL.query
MySQL.Sync.fetchAll = MySQL.query.await


exports.oxmysql:scalar
MySQL.Async.fetchScalar = MySQL.scalar
MySQL.Sync.fetchScalar = MySQL.scalar.await


exports.oxmysql:single
MySQL.Async.fetchSingle = MySQL.single
MySQL.Sync.fetchSingle = MySQL.single.await


exports.oxmysql:insert
MySQL.Async.insert = MySQL.insert
MySQL.Sync.insert = MySQL.insert.await


exports.oxmysql:update
MySQL.Async.execute = MySQL.update
MySQL.Sync.execute = MySQL.update.await


exports.oxmysql:transaction
MySQL.Async.transaction = MySQL.transaction
MySQL.Sync.transaction = MySQL.transaction.await


exports.oxmysql:prepare
MySQL.Async.prepare = MySQL.prepare
MySQL.Sync.prepare = MySQL.prepare.await
```

The previous `Sync` export variants are now `_async` to correctly reflect their behaviour (Lua automatically awaits these with promises).

**Comment by evanillaa** [comment]
I follow your work and admire it, thank you

**Comment by GhzGarage** [comment]
Update has been completed

**Pull request closed without merging**
