### PR TITLE
add Tax options

### PR DESCRIPTION
**Pull request by darknight2590**
**Describe Pull request**

Add tax system

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by Mitroxs — APPROVED** [review]

**Comment by maxtzy** [comment]
how to use that ?

**Comment by xenfovn** [comment]
what this ?

**Comment by Mojito-Fivem** [comment]
What purpose does this serve which benefits the framework as a whole?

**Comment by DaShizz** [comment]
@Mojito-Fivem it servers as a "reality" addon imo.

**Comment by Mojito-Fivem** [comment]
> @Mojito-Fivem it servers as a "reality" addon imo.

The actual code in this pull request serves no purpose, other than adding bloat code that 1 script uses. I don't see how this benefits the framework

**Comment by DaShizz** [comment]
> > @Mojito-Fivem it servers as a "reality" addon imo.
> 
> The actual code in this pull request serves no purpose, other than adding bloat code that 1 script uses. I don't see how this benefits the framework

I agree with you. I was simply pointing out the need for it!

**Pull request closed without merging**
