### PR TITLE
Fix give fuel

### PR DESCRIPTION
**Pull request by milotiro95**
Fix for /car admin commands getting fuel not working. Now it does :)

### CODE REVIEW

**Comment by BerkieBb** [comment]
This doesn't fix anything, LegacyFuel does the exact same thing, but LegacyFuel also sets an extra variable so it saves how much fuel there is for the resource itself to manage all fuel

**Comment by BerkieBb** [comment]
If you look at the [SetFuel export in LegacyFuel](https://github.com/qbcore-framework/LegacyFuel/blob/master/functions/functions_client.lua#L7) you can see it does the exact same

**Comment by BerkieBb** [comment]
I can't explain that, all I can say is that I've never had this issue

**Comment by milotiro95** [comment]
I have don't test but perhaps it's simple as that 
`SetVehicleFuelLevel(vehicle, 100 + 0.0)`

**Pull request closed without merging**
