### PR TITLE
Add GetPlayerByLicense function

### PR DESCRIPTION
**Pull request by DaniGP17**
## Description
This pull request introduces a new function called GetPlayerByLicense. The purpose of this function is to retrieve player data based on their license.

Change Summary:
The addition of the GetPlayerByLicense function enhances the functionality of qb-core by allowing developers to easily access player data using their license as a parameter. This feature provides a streamlined method for retrieving specific player information, contributing to the overall efficiency and convenience of the qb-core framework.

## Code Example
`local Player = QBCore.Functions.GetPlayerByLicense('license:xxxxxxxxxxxxxxxxxxxx')`

## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by DaniGP17** [comment]
Ready

**Comment by GhzGarage** [comment]
That brings up a good point, could you update that in your PR to change the other as well. Thank you!

**Comment by DaniGP17** [comment]
> That brings up a good point, could you update that in your PR to change the other as well. Thank you!

Done, sorry for being late

**Comment by DaniGP17** [comment]
Is there any progress?

**Comment by DaniGP17** [comment]
Any update with this?

**Pull request merged**
