### PR TITLE
Add logic for manage locales

### PR DESCRIPTION
**Pull request by lunatrik**
add generic function for translation string in QBShared.lua. 
add conf…iguration enviroments Locale

### CODE REVIEW

**Review by lunatrik — COMMENTED** [review]
add functions for manage locale in every qb resource

**Comment by JericoFX** [comment]
Can you provide an actually example, like you need another file right? it.lua or something like that?

**Comment by lunatrik** [comment]
the main change in qb-core is add 2 function in QBShared

QBShared._
QBShared._U

I know this change is currently on hold by BerkieBb. I am continuing with the translations of other scripts. At the moment the shared.lua with all its objects has not been translated. Check pull requests from other scripts like atms / drugs / garages

**Comment by vanillla1** [comment]
But this is not esx
The programmers here love the way it's built qbcore without _U

**Comment by Mr-Pleb** [comment]
I think this may improve the end-user experience by a lot and perhaps ESX servers with different languages will want to transform.

**Pull request closed without merging**
