### PR TITLE
Cash as items in inventory

### PR DESCRIPTION
**Pull request by KingRyuShin**
I know this is not clean but it work.
This enable you to set your cash as a item insted of the hud
must create a cash.png image inside your qb-inventory

### CODE REVIEW

**Review by Muri22 — APPROVED** [review]

**Comment by Mojito-Fivem** [comment]
rebase your PR g

**Comment by Zviux** [comment]
image
don't work

**Comment by FjamZoo** [comment]
QBCore has stated multiple times that having cash as items gives multiple issues as there will be ways to duplicate items and this could and would lead to more issues in the future.

**Comment by IdrisDose** [comment]
We're not going to include cash as an item, feel free to add it as a snippet though.

**Pull request closed without merging**
