### PR TITLE
Fixed da.lua

### PR DESCRIPTION
**Pull request by 7R3C3**
Fixed da.lua

### CODE REVIEW

**Comment by nullvariable** [comment]
hi @7R3C3 this looks good, could you rebase the change against the main branch again so we can get the linter passing?

**Comment by 7R3C3** [comment]
> hi @7R3C3 this looks good, could you rebase the change against the main branch again so we can get the linter passing?

How in the world do i do that?

**Comment by GhzGarage** [comment]
> > hi @7R3C3 this looks good, could you rebase the change against the main branch again so we can get the linter passing?
> 
> How in the world do i do that?

image

**Comment by FjamZoo** [comment]
Hello could you please update to fix the LInt requests that kakarot Screenshotted above?

**Comment by 7R3C3** [comment]
It is pulled directly from the en.lua so there shouldnt be any issues

**Pull request merged**
