### PR TITLE
Camber DB entry

### PR DESCRIPTION
**Pull request by S4pphiree**
Describe Pull request
Saw that qb-tunerchip doesn't sync in anyway anything so I decided to add some lines of code just to make it possible

Questions (please complete the following information):

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes (Be honest)
Does your code fit the style guidelines? yes
Does your PR fit the contribution guidelines? yes

### CODE REVIEW

**Comment by Branqueador** [comment]
It doens't work, when you'r going to save a car in the garage it gives an error

**Comment by S4pphire-hue** [comment]
> 

Strange, are you using the latest version of vstancer?

**Comment by Branqueador** [comment]
No I don’t even a resource called vstancer
And with that what you are saying is that this pr would work if we have vstancer

**Comment by S4pphire-hue** [comment]
> No I don’t even a resource called vstancer And with that what you are saying is that this pr would work if we have vstancer

Exactly, qb-tunerchip uses vstancer exports to add camber to the wheels, I'm guessing the error it's giving you is something about vstancer

**Comment by SW1FT** [comment]
@S4pphire-hue You're right, but also, QBCore's recipe doesn't download with vstancer nor is there a vstancer QBCore fork.

**Comment by S4pphire-hue** [comment]
> @S4pphire-hue You're right, but also, QBCore's recipe doesn't download vstancer nor is there a vstancer QBCore fork.

Isn't this a Fork? https://github.com/qbcore-framework/fivem-vstancer
Just asking because I'm pretty new at doing PRs on GitHub

**Comment by BerkieBb** [comment]
A fork doesn't mean the recipe downloads it

**Comment by S4pphire-hue** [comment]
> A fork doesn't mean the recipe downloads it

I know that, but why doesn't the recipe download it if qb-tunerchip makes use of it?

**Comment by SW1FT** [comment]
> > @S4pphire-hue You're right, but also, QBCore's recipe doesn't download vstancer nor is there a vstancer QBCore fork.
> 
> @SW1FT Isn't this a Fork? https://github.com/qbcore-framework/fivem-vstancer Just asking because I'm pretty new at doing PRs on GitHub

I had no idea that existed, I stand corrected. Maybe someone should make a PR over at the recipe's repo and get it sorted.

**Pull request closed without merging**
