### PR TITLE
Add paychecks from society account

### PR DESCRIPTION
**Pull request by Brady-F**
**Describe Pull request**
Added config option for paychecks to be taken from society account when the player is employed by a society.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] Yes
- Does your code fit the style guidelines? [yes/no] Yes
- Does your PR fit the contribution guidelines? [yes/no] Yes

### CODE REVIEW

**Comment by GhzGarage** [comment]
Add a check if the account exists

**Comment by Brady-F** [comment]
> Add a check if the account exists

I believe it does...
This line:
`if account ~= 0 then`

should check if the account exists. If account is 0 then it does not exist.

**Comment by darknight2590** [comment]
beauty of suggestion

**Comment by GhzGarage** [comment]
Change to false by default please if you would

**Comment by Brady-F** [comment]
> Change to false by default please if you would

Fixed!

**Comment by evanillaa** [comment]
thank you

**Pull request merged**
