### PR TITLE
Fixed helicopters not going air depot

### PR DESCRIPTION
**Pull request by buntyverma69**
Describe Pull request
 I am trying to figure it out why helicopters not going air depot ! category names are miss matching with garages.
 
Questions (please complete the following information):

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] yes
Does your code fit the style guidelines? [yes/no] yes
Does your PR fit the contribution guidelines? [yes/no] yes

### CODE REVIEW

**Comment by milotiro95** [comment]
I think there is a same problem with the boat. You can put them out of the garage but cannot put them in it said unreconized vehicle.

**Comment by buntyverma69** [comment]
> I think there is a same problem with the boat. You can put them out of the garage but cannot put them in it said unreconized vehicle.

I fixed it check lasted pull req

**Comment by buntyverma69** [comment]
@IdrisDose  Please Review this

**Comment by buntyverma69** [comment]
@IdrisDose see this hope you understand the issues https://youtu.be/C5sw0eSZXtY

**Pull request merged**
