### PR TITLE
Locale Convar support

### PR DESCRIPTION
**Pull request by Sna-aaa**
Support for Convar for the locale selection and adaptation of locales

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by IdrisDose** [comment]
Needs updating with latest prs - Also can you submit a PR to the TXAdminRecipe for Default Convar.

**Comment by Sna-aaa** [comment]
@IdrisDose Updated, i continue with TxAdminRecipe

**Comment by GhzGarage** [comment]
@Sna-aaa Can you fix this

**Comment by Sna-aaa** [comment]
Normally it is updated now @GhzGarage

**Review by CodexisPhantom — APPROVED** [review]
A really important pr to do. This is fantastic for all user 👍

**Comment by Sna-aaa** [comment]
@GhzGarage Done ;)

**Review by D4isDAVID — CHANGES_REQUESTED** [review]

**Review by D4isDAVID — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
