### PR TITLE
Adding possibility to manage cash from inventory

### PR DESCRIPTION
**Pull request by skrilax91**
**Describe Pull request**
I had the opportunity to see many people ask how to manage cash from inventory rather than a simple variable. Today I come to bring my contribution to the project by proposing to add this feature.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

### CODE REVIEW

**Comment by kaptenecha** [comment]
if using qb-hud, you need to change server.lua

> local cashamount = Player.PlayerData.money.cash

to

> local cashamount = Player.Functions.GetItemByName("cash").amount

it's can sync your in game money hud at top-right

**Comment by GhzGarage** [comment]
Has conflicts

**Comment by Diversey** [comment]
I'd love to see this working

**Comment by BerkieBb** [comment]
I will implement this sometime next month or the month after

**Comment by skrilax91** [comment]
I could face some compatibility issues with some resources using the variable in the metadata directly instead of using the functions provided by QB-core. It might be interesting to issue a warning message about possible compatibility problem

**Comment by hawbashanwar98** [comment]
dear my friends, i used these codes and have a problem with buying items without cash money.
could you please solve this also

**Pull request closed without merging**
