### PR TITLE
Feat(events): Better TPM Event

### PR DESCRIPTION
**Pull request by Mycroft-Studios**
**Describe Pull request**
Makes TPM much nicer :)

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] No
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes

### CODE REVIEW

**Comment by braydxnn** [comment]
I feel like I've seen this code before?

**Comment by Mycroft-Studios** [comment]
> I feel like I've seen this code before?

Its called open source code :)

**Review by ihyajb — APPROVED** [review]

**Review by BerkieBb — APPROVED** [review]

**Review by ItsANoBrainer — APPROVED** [review]

**Comment by GhzGarage** [comment]
@IdrisDose Let's make a decision on this and get it pushed

**Comment by IdrisDose** [comment]
This pr needs an update however I don't mind for a more "rp" effect.

**Comment by GhzGarage** [comment]
I ended up just using it on redm lol

**Comment by BerkieBb** [comment]
@GhzGarage conflicts are fixed, so this should be good to go

**Pull request merged**
