### PR TITLE
add return closetDistance

### PR DESCRIPTION
**Pull request by NEvermeant77**
i guess maybe you missed 1 return?

### CODE REVIEW

**Comment by NEvermeant77** [comment]
example:
in qb-ambulance there is some function require the closetdistance
local closestPed, closestDistance = QBCore.Functions.GetClosestPed(coords, PlayerPeds)

**Comment by Eralpozcan** [comment]
I guess they don't find it right to add this. It's obviously causing a problem. Because I opened the same PR before, today it was closed and not added. #163

**Comment by NEvermeant77** [comment]
i see thank man

**Comment by GhzGarage** [comment]
I will look into this. All previous issues and pr’s were closed before this last big update because a lot of code structure changed

**Comment by Eralpozcan** [comment]
@GhzGarage Then if the same problems remain with the current code structure, should we open PR again?

**Comment by GhzGarage** [comment]
Yes of course

**Comment by GhzGarage** [comment]
Also @NEvermeant77 have you tested this pull request or just guessing that that variable should be returned?

**Comment by Eralpozcan** [comment]
@GhzGarage I will tested. We can process according to the distance range. So it's working.

Basicly Example:

```
local closestPed, closestDistance = QBCore.Functions.GetClosestPed(coords, PlayerPeds)
if closestDistance < 5 then
 //bla bla bla whatever you want to do to the one near you.
else
//There is no one near.
end
```

I think this also solves #218 
But I haven't tried that for this problem. I just used it in police job before.

Here we can get reference : [ESX Docs](https://esx-framework.github.io/es_extended/client/functions/game/getclosestplayer/)

**Pull request closed without merging**
