### PR TITLE
Spawning Cars server side to make persistent vehicles server wide. (Not tested in qbcore)

### PR DESCRIPTION
**Pull request by xDope7137**

### CODE REVIEW

**Comment by xDope7137** [comment]
`Player.Functions.GetItem` function added which returns count to 0 if player don't have the item

**Comment by xenfovn** [comment]
it shit bro ,i cant spawn vehicle with this code

**Comment by xDope7137** [comment]
@xenfovn updated

**Comment by xenfovn** [comment]
@xDope7137 please take a moment to check this, have you tested it?

**Pull request closed without merging**
