### PR TITLE
log for ToggleDuty

### PR DESCRIPTION
**Pull request by evanillaa**
**Describe Pull request**

Create a time log for the event

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by evanillaa** [comment]
https://github.com/qbcore-framework/qb-smallresources/pull/150

**Comment by GhzGarage** [comment]
Pretty sure these are backwards

**Comment by IdrisDose** [comment]
Yeah, they are backwards my guy.

**Comment by izMystic** [comment]
Yeah, they are backwards my guy.

**Pull request closed without merging**
