### PR TITLE
feat: Add Filter to QBCore export

### PR DESCRIPTION
**Pull request by Jamie9192**
Pass the structure of QBCore, making the value you want equal either "all" or true. Examples in main.lua on client and server side

## Description

Adds ability to filter the core object when importing. Thus reducing memory usage. 
Fixes: importing large object of unneccessary data when not required

## Checklist

- [ X] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [X ] My code fits the style guidelines.
- [X ] My PR fits the contribution guidelines.

### CODE REVIEW

**Review by ChristianBDev — APPROVED** [review]
Tested LGTM, Good performance, noticeably a difference 
image

**Comment by Jamie9192** [comment]
image_2024-07-11_105110109

Testing shows major improvement only importing Functions. Shared seems to be the main cause of large object. This being client side testing only.

**Comment by GhzGarage** [comment]
@Jamie9192 Could you just add the code to the export with an early return of the full core object if no filters

**Comment by Jamie9192** [comment]
> @Jamie9192 Could you just add the code to the export with an early return of the full core object if no filters

Sure, but the filter function is not _just_ for the core object, and could potentially be used in other resources

**Review by Mycroft-Studios — APPROVED** [review]
The only thing i would maybe like to see, is the filter function itself being moved to QBShared, as maybe a:
`QBShared.FilterTable`

**Comment by Jamie9192** [comment]
> The only thing i would maybe like to see, is the filter function itself being moved to QBShared, as maybe a: `QBShared.FilterTable`

This would make sense more so if the core exports were shared, but they are separated, and Shared holds data rather than functions.

As it is a function, I believe its best to be added as such

**Comment by QBStevie** [comment]
.

**Pull request closed without merging**
