### PR TITLE
New ways to editing datas

### PR DESCRIPTION
**Pull request by negbook**

### CODE REVIEW

**Comment by BerkieBb** [comment]
Can you explain the change you made?

**Comment by negbook** [comment]
> Can you explain the change you made?

Load datas from csv

**Comment by BerkieBb** [comment]
I want to know how this would be more useful

**Comment by negbook** [comment]
> I want to know how this would be more useful

It would not be more useful if the datas included too many json.encode datas at this moment.

**Comment by negbook** [comment]
Also editing datas from csv is more friendly for server owner but less friendly for the developer.It's depends on qb-core directions.

**Comment by BerkieBb** [comment]
But can you explain why and how this helps in as much detail as you can?

**Comment by negbook** [comment]
No,I can not.It just an idea, a concept.

**Pull request closed without merging**
