### PR TITLE
 Duplicate license check: By MrCrowley

### PR DESCRIPTION
**Pull request by gononono64**
## Description

Duplicate license check just...doesnt work
Because of that this happens: https://www.youtube.com/watch?v=U1Pxpxuj7-o
If you bother to look into this you will realize you should merge this pretty much asap

PS I got lazy and rewrote what i did through the github editor. Its just a few minor modifications that i did. I also did these modifications on another server that was having the same issue. Person who brought it to my attention.

Please make sure i didnt miss anything. AKA make sure to test it
## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by gononono64** [comment]
There, next time dont approve things the linter doesnt accept...her der

**Comment by iboss21** [comment]
we personally tested it on our server and fixed it now. thanks to MrCrowley

**Review by Sh3ldar — APPROVED** [review]
tested and working the commands.lua part is not needed

**Comment by gononono64** [comment]
> tested and working the commands.lua and functions.lua part is not needed for merge

commands is needed for linter, functions there was a redundant check

**Review by ChristianBDev — APPROVED** [review]
LGTM | Tested and it works

**Comment by Qwerty1Verified** [comment]
What part of the original code stops it from working? Is it the retrieving of the licenses before waiting that's stopping it?

**Comment by ChristianBDev** [comment]
> What part of the original code stops it from working? Is it the retrieving of the licenses before waiting that's stopping it?

This is where it is stopping it, 
```
-- if GetConvarInt('sv_fxdkMode', false) then
    --     license = 'license:AAAAAAAAAAAAAAAA' -- Dummy License
    -- end

    if not license then
        deferrals.done(Lang:t('error.no_valid_license'))
    elseif QBConfig.Server.CheckDuplicateLicense and QBCore.Functions.IsLicenseInUse(license) then
```

**Comment by Qwerty1Verified** [comment]
Checking that convar should be doable, this is the normal documented usage though `local fxdkMode = GetConvarInt('sv_fxdkMode', 0) == 1`

**Comment by gononono64** [comment]
> Checking that convar should be doable, this is the normal documented usage though `local fxdkMode = GetConvarInt('sv_fxdkMode', 0) == 1`

For what purpose?

**Comment by Qwerty1Verified** [comment]
Its purpose is to allow the usage of the Cfx.re Development Kit (FxDK)

**Comment by gononono64** [comment]
> Its purpose is to allow the usage of the Cfx.re Development Kit (FxDK). The edit on line 50 of the `events.lua` file also seems unnecessary.
QBConfig.Server.CheckDuplicateLicense is definitely needed as its checking the config as it should. The previous was a typo

**Comment by Qwerty1Verified** [comment]
It was previously checking the config through `QBCore.Config`

**Comment by gononono64** [comment]
> It was previously checking the config through `QBCore.Config`

image
image

**Comment by Qwerty1Verified** [comment]
https://github.com/qbcore-framework/qb-core/blob/a866b1a0492a1d01678bc765b3beda5f70bc3ebf/server/main.lua#L2
`QBCore.Config` is a variable alias defined by `QBConfig`

**Comment by gononono64** [comment]
> https://github.com/qbcore-framework/qb-core/blob/a866b1a0492a1d01678bc765b3beda5f70bc3ebf/server/main.lua#L2
> 
> `QBCore.Config` is a variable alias defined by `QBConfig`

Well i can tell you from experience, being a developer and having to figure out what links where without any search options, is simply bad design. Makes it much harder to decode. At this point take it or leave it

**Comment by Qwerty1Verified** [comment]
It's usually just a matter of best practice, hence why getters and setters exist to prevent access to the original data structure. People write code differently, but this is usually the practice that is followed. When most of the other code uses `QBCore.Config`, it can be assumed that it works if it hasn't been modified, and then of course a quick search for `QBCore.Config` would reveal that it is a real variable and has a role

**Comment by gononono64** [comment]
> It's usually just a matter of best practice, hence why getters and setters exist to prevent access to the original data structure. People write code differently, but this is usually the practice that is followed. When most of the other code uses `QBCore.Config`, it can be assumed that it works if it hasn't been modified, and then of course a quick search for `QBCore.Config` would reveal that it is a real variable and has a role

image

**Comment by Qwerty1Verified** [comment]
Yeah that's why I said different people write code differently and that most of the other code uses `QBCore.Config`. Simply trying to follow best practice, and that's just a few occasions where it's using `QBConfig`. I'm glad you found the cause of the bug though

**Comment by Qwerty1Verified** [comment]
Has it been tested since the convar check was added back in? It'll be nice to see a bug like this fixed

**Comment by iboss21** [comment]
I m glad its fixed and servers owners as myself can be relaxed. Thank you guys and thanks to QBCore Community for this fast response and fixing it. 

Truly appreciated.

**Comment by gononono64** [comment]
> Has it been tested since the convar check was added back in? It'll be nice to see a bug like this fixed

yes

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-core/commit/d7323ba147c6e135aa4df1910a3c4ff7eedac192

**Pull request closed without merging**
