### PR TITLE
[Update] Missing Vehicle Properties

### PR DESCRIPTION
**Pull request by ItsANoBrainer**
Added proper support for missing or unfinished vehicle property saving/getting:

- neons enabled/disabled
- tire health
- tire burst state
- tire burst completely
- oil level
- wheel size
- wheel width
- headlight color
- interior color
- modkit 17, 19, 21, 47, 49
- livery roof
- tankHealth

- Set LegacyFuel on setting fuel level

### CODE REVIEW

**Review by JajarGaming — APPROVED** [review]
LGTM

**Comment by Mojito-Fivem** [comment]
Is it a great idea to have LegacyFuel be a dependency of qb-core? Maybe in other resources sure but I don't think it's a great idea to restrict versatility of the base framework in my opinion

**Comment by ItsANoBrainer** [comment]
> 

I mean, LegacyFuel is apart of the qb-core framework project repo and tx-admin recipe. At this point isn't it already a dependency?

**Comment by JnKTechstuff** [comment]
> Is it a great idea to have LegacyFuel be a dependency of qb-core? Maybe in other resources sure but I don't think it's a great idea to restrict versatility of the base framework in my opinion

I would honestly just have a Config option for them to use their fuel script export of their choice. Like how some escrow scripts have their stuff setup.

**Comment by darknight2590** [comment]
Thank you for the beautiful edits
We are currently using LegacyFuel 
I don't know why the words are useful in responses
The project originally used this resource LegacyFuel 
But there is a saying that says I was created to object

**Review by darknight2590 — APPROVED** [review]

**Comment by IdrisDose** [comment]
Hey, I like the edit, however, Mojito is correct can you remove the LegacyFuel export from the core please :)

**Comment by evanillaa** [comment]
@ItsANoBrainer

**Comment by ItsANoBrainer** [comment]
Done

@IdrisDose @evanillaa

**Comment by BerkieBb** [comment]
Instead of removing it, you could use the native SetVehicleFuelLevel

**Comment by ItsANoBrainer** [comment]
> Instead of removing it, you could use the native SetVehicleFuelLevel

Good idea, for some reason I thought that was already done, added.

**Pull request merged**
