### PR TITLE
Bypass for loading QBCore in FxDK

### PR DESCRIPTION
**Pull request by MannaMuncher**
FxDK does not include license identifiers by default and thus breaks scripts that utilize those. Without this you will get the "No valid Rockstar license" error when connecting. This fix was not my own I found it in the post linked below and tested myself.

https://forum.cfx.re/t/connection-rejected-by-server-fxdk/2504365/5

### CODE REVIEW

**Comment by ChatDisabled** [comment]
Interesting problem indeed. Besides the function `QBCore.Functions.GetIdentifier` there are some instances where the native `GetPlayerIdentifiers` also gets used within QBCore. Definitely something the team should look into.

Update your branch though! Mind the linting issues as well @MannaMuncher.
alt text

**Comment by D4isDAVID** [comment]
@ChatDisabled
The linting issues are most likely caused by the previous merge, so just updating the branch should fix it

**Comment by MannaMuncher** [comment]
I was in the middle of moving but I fixed it now.

**Comment by MannaMuncher** [comment]
You guys should be able to update branches from the PR view the merge blocking is unnecessary.

**Review by jeann2013 — APPROVED** [review]

**Review by D4isDAVID — APPROVED** [review]
LGTM

**Review by Z3rio — APPROVED** [review]
Code looks good to me, although I have not been able to test it myself with FXDK.
I will have to trust the other testers that have tried it with FXDK.

**Pull request merged**
