### PR TITLE
Update de.lua

### PR DESCRIPTION
**Pull request by CptNoHand**
sounds better like this

### CODE REVIEW

**Review by Z3rio — APPROVED** [review]
Looks good to me, if someone that actually knows this language can confirm that it is better then that would be good.
I dont see any issues with the code or such though, just unsure if its better then the original or not :)

**Review by TheRealCasiv2 — CHANGES_REQUESTED** [review]
Looks good!
But i suggest changing the duty messages to:
"Du befindest dich nun im Dienst!" and "Du befindest dich nun nicht mehr im Dienst!"

But otherwise it looks really good

**Review by TheRealCasiv2 — CHANGES_REQUESTED** [review]
It's better but still has a grammatical error, correct would be like i said: "Du befindest dich nun im Dienst!" and "Du befindest dich nun nicht mehr im Dienst!". So replace the "jetzt" with "nun"

Then it would be correct.

**Review by TheRealCasiv2 — APPROVED** [review]
It's correct now. 
I Approve.

**Pull request merged**
