### PR TITLE
add new truck to show in trucker shop

### PR DESCRIPTION
**Pull request by jeann2013**
## Description
Add news cars in list vehicle to sell truck in truck motor shop, you can see this PR https://github.com/qbcore-framework/qb-vehicleshop/pull/263

### CODE REVIEW

**Comment by r0adra93** [comment]
Gotta use category commercial

**Comment by r0adra93** [comment]
Trailers use category utility

**Comment by jeann2013** [comment]
> utility

What you means?

**Comment by r0adra93** [comment]
Supported vehicle categories in gta-v shpuld be all lowecase.

0: Compacts  
1: Sedans  
2: SUVs  
3: Coupes  
4: Muscle  
5: SportsClassics  
6: Sports  
7: Super  
8: Motorcycles  
9: Offroad  
10: Industrial  
11: Utility  
12: Vans  
13: Cycles  
14: Boats  
15: Helicopters  
16: Planes  
17: Service  
18: Emergency  
19: Military  
20: Commercial  
21: Trains  
22: OpenWheel

**Comment by r0adra93** [comment]
Gotta also change garages to create special garages that only allow vehicles with the id of 11 and 20 to park at truck parking gargaes as 11 and 20 correlate to the category of utility and commercial in vehicles.lua

**Comment by r0adra93** [comment]
Here is an example for you to follow:

    ["phantom"] = {
        ["name"] = "Phantom",
        ["brand"] = "JoBuilt",
        ["model"] = "phantom",
        ["price"] = 90000,
        ["category"] = "commercial", -- <<< This is a GTA V category must match GTA V or things break!
        ["hash"] = `phantom`,
        ["shop"] = {"truck"}
    },
    ["trailers"] = {
        ["name"] = "Canvas Trailer",
        ["brand"] = "BigDawg",
        ["model"] = "trailers",
        ["price"] = 75000,
        ["category"] = "utility", -- <<< This is a GTA V category must match GTA V or things break!
        ["hash"] = `trailers`,
        ["shop"] = {"truck"}
    },

**Comment by r0adra93** [comment]
I actually went through and did this for you. All you have to do is include it into your PR.


    ['hauler'] = {
        ['name'] = 'Hauler',
        ['brand'] = 'Hauler',
        ['model'] = 'hauler',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `Hauler`,
        ['shop'] = 'truck',
    },
    ['packer'] = {
        ['name'] = 'packer',
        ['brand'] = 'packer',
        ['model'] = 'packer',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `packer`,
        ['shop'] = 'truck',
    },
    ['stockade'] = {
        ['name'] = 'stockade',
        ['brand'] = 'Brute',
        ['model'] = 'stockade',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `stockade`,
        ['shop'] = 'truck',
    },
    ['biff'] = {
        ['name'] = 'biff',
        ['brand'] = 'Brute',
        ['model'] = 'biff',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `biff`,
        ['shop'] = 'truck',
    },
    ['phantom'] = {
        ['name'] = 'Phantom',
        ['brand'] = 'Phantom',
        ['model'] = 'phantom',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `Phantom`,
        ['shop'] = 'truck',
    },
    ['phantom3'] = {
        ['name'] = 'Phantom Custom',
        ['brand'] = 'Phantom Custom',
        ['model'] = 'phantom3',
        ['price'] = 110000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `Phantom Custom`,
        ['shop'] = 'truck',
    },
    ['benson'] = {
        ['name'] = 'Benson',
        ['brand'] = 'benson',
        ['model'] = 'benson',
        ['price'] = 55000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `benson`,
        ['shop'] = 'truck',
    },
    ['mule'] = {
        ['name'] = 'Mule',
        ['brand'] = 'mule',
        ['model'] = 'mule',
        ['price'] = 40000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `mule`,
        ['shop'] = 'truck',
    },
    ['mule2'] = {
        ['name'] = 'Mule2',
        ['brand'] = 'mule2',
        ['model'] = 'mule2',
        ['price'] = 40000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `mule2`,
        ['shop'] = 'truck',
    },
    ['mule3'] = {
        ['name'] = 'Mule3',
        ['brand'] = 'mule3',
        ['model'] = 'mule3',
        ['price'] = 40000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `mule3`,
        ['shop'] = 'truck',
    },
    ['pounder'] = {
        ['name'] = 'Pounder',
        ['brand'] = 'pounder',
        ['model'] = 'pounder',
        ['price'] = 55000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `pounder`,
        ['shop'] = 'truck',
    },
    ['boxville'] = {
        ['name'] = 'Boxville',
        ['brand'] = 'Brute',
        ['model'] = 'boxville',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville`,
        ['shop'] = 'truck',
    },
    ['boxville2'] = {
        ['name'] = 'Boxville2',
        ['brand'] = 'Brute',
        ['model'] = 'boxville2',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville2`,
        ['shop'] = 'truck',
    },
    ['boxville3'] = {
        ['name'] = 'Boxville3',
        ['brand'] = 'Brute',
        ['model'] = 'boxville3',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville3`,
        ['shop'] = 'truck',
    },
    ['boxville4'] = {
        ['name'] = 'Boxville4',
        ['brand'] = 'Brute',
        ['model'] = 'boxville4',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville4`,
        ['shop'] = 'truck',
    },
    ['boxville5'] = {
        ['name'] = 'Armored Boxville,
        ['brand'] = 'Brute',
        ['model'] = 'boxville5',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville4`,
        ['shop'] = 'truck',
    },
    ['pony'] = {
        ['name'] = 'Pony,
        ['brand'] = 'Brute',
        ['model'] = 'pony',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `pony`,
        ['shop'] = 'truck',
    },
    ['pony2'] = {
        ['name'] = 'Pony 2,
        ['brand'] = 'Brute',
        ['model'] = 'pony2',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `pony2`,
        ['shop'] = 'truck',
    },
    ['taco'] = {
        ['name'] = 'Taco Truck,
        ['brand'] = 'Brute',
        ['model'] = 'taco',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Food Truck',
        ['hash'] = `taco`,
        ['shop'] = 'truck',
    },
    ['cutter'] = {
        ['name'] = 'cutter',
        ['brand'] = 'HVY',
        ['model'] = 'cutter',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `cutter`,
        ['shop'] = 'truck',
    },
    ['handler'] = {
        ['name'] = 'Dock Handler',
        ['brand'] = 'HVY',
        ['model'] = 'handler',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `handler`,
        ['shop'] = 'truck',
    },
    ['bulldoze'] = {
        ['name'] = 'Bulldozer',
        ['brand'] = 'HVY',
        ['model'] = 'bulldoze',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `bulldoze`,
        ['shop'] = 'truck',
    },
    ['dump'] = {
        ['name'] = 'HVY Dump Truck (Off Road)',
        ['brand'] = 'HVY',
        ['model'] = 'dump',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `dump`,
        ['shop'] = 'truck',
    },
    ['flatbed'] = {
        ['name'] = 'Flatbed Truck',
        ['brand'] = 'MTL',
        ['model'] = 'flatbed',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `flatbed`,
        ['shop'] = 'truck',
    },
    ['flatbed'] = {
        ['name'] = 'Flatbed Truck',
        ['brand'] = 'MTL',
        ['model'] = 'flatbed',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `flatbed`,
        ['shop'] = 'truck',
    },
    ['guardian'] = {
        ['name'] = 'Guardian',
        ['brand'] = 'Vapid’,
        ['model'] = 'guardian',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `guardian`,
        ['shop'] = 'truck',
    },
    ['mixer'] = {
        ['name'] = 'Cement Mixer',
        ['brand'] = 'HVY',
        ['model'] = 'mixer',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `mixer`,
        ['shop'] = 'truck',
    },
    ['mixer2'] = {
        ['name'] = 'Mixer2',
        ['brand'] = 'HVY',
        ['model'] = 'mixer2',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `mixer2`,
        ['shop'] = 'truck',
    },
    ['rubble'] = {
        ['name'] = 'Jobuilt Dump Truck (Street Legal)',
        ['brand'] = 'Jobuilt’,
        ['model'] = 'rubble',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `rubble`,
        ['shop'] = 'truck',
    },
    ['tiptruck'] = {
        ['name'] = 'Brute Dump Truck (Street Legal)',
        ['brand'] = 'Brute’,
        ['model'] = 'tiptruck',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `tiptruck`,
        ['shop'] = 'truck',
    },
    ['tiptruck2'] = {
        ['name'] = 'MTL Dump Truck (Street Legal)',
        ['brand'] = 'MTL’,
        ['model'] = 'tiptruck2',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `tiptruck2`,
        ['shop'] = 'truck',
    },

**Comment by jeann2013** [comment]
@r0adra93 ok cool

**Review by r0adra93 — COMMENTED** [review]
Fix your linting and I will go ahead and test it out.

**Review by r0adra93 — APPROVED** [review]

**Comment by KSJDiamondGaming** [comment]
Further to your PR, pointless pulling my own. Sorry for jumping on yours.. these changes need to me ammeded

['boxville5'] = {
    ['name'] = 'Armored Boxville,
    ['brand'] = 'Brute',
    ['model'] = 'boxville5',
    ['price'] = 45000,
    ['category'] = 'vans',
    ["categoryLabel"] = 'Vans',
    ['hash'] = `boxville4`,
    ['shop'] = 'truck',
},
To
['boxville5'] = {
    ['name'] = 'Armored Boxville,
    ['brand'] = 'Brute',
    ['model'] = 'boxville5',
    ['price'] = 45000,
    ['category'] = 'vans',
    ["categoryLabel"] = 'Vans',
    ['hash'] = `boxville5`,
    ['shop'] = 'truck',
},
['bulldoze'] = {
    ['name'] = 'Bulldozer',
    ['brand'] = 'HVY',
    ['model'] = 'bulldoze',
    ['price'] = 30000,
    ['category'] = 'industrial',
    ["categoryLabel"] = 'Industrial',
    ['hash'] = `bulldoze`,
    ['shop'] = 'truck',
},
TO
['bulldozer'] = {
    ['name'] = 'Bulldozer',
    ['brand'] = 'HVY',
    ['model'] = 'bulldozer',
    ['price'] = 30000,
    ['category'] = 'industrial',
    ["categoryLabel"] = 'Industrial',
    ['hash'] = `bulldozer`,
    ['shop'] = 'truck',
},
Boxville 5 was carrying the hash of boxville 4 and bulldozer was correct in spelling under [name] but not in [hash] [model] or [spawn]

atleast by me making these changes i could see vehicles in shop and spawn them as ive gone through the whole list to change prices etc.

**Comment by Z3rio** [comment]
Outdated PR, these seem to have already been added by now :)

**Pull request closed without merging**
