### PR TITLE
Backwards compatibility for vehicles.lua

### PR DESCRIPTION
**Pull request by xDope7137**
## Description

you can just drag and drop the vehicles from older vehicles.lua now

## Checklist

- [x ] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by MoskalykA** [comment]
bad idea https://stackoverflow.com/questions/71276468/what-is-the-fastest-way-to-go-through-an-array-table-with-numeric-indices

**Comment by xDope7137** [comment]
> bad idea https://stackoverflow.com/questions/71276468/what-is-the-fastest-way-to-go-through-an-array-table-with-numeric-indices

buddy read the whole topic. they are enumerating 100,000+ values. People do not have more than 500 vehicles in that file.

by that logic, nothing should be using ipairs. It does not sense to make it work for all small sized tables.

Besides, are you going to let all server owners to convert their whole car tables to new layout? To save 0.2ms compute time? Just one time every restart? smh

**Comment by xDope7137** [comment]
image

**Comment by MoskalykA** [comment]
> you can just drag and drop the vehicles from older vehicles.lua now

the micro-optimisation is already done, so your argument doesn't make sense.

**Comment by xDope7137** [comment]
qb dead?

**Comment by xDope7137** [comment]
qb dead dead

**Pull request closed without merging**
