### PR TITLE
spawn and delete object local

### PR DESCRIPTION
**Pull request by xenfovn**
spawn and delete object local

### CODE REVIEW

**Comment by JericoFX** [comment]
hi, where did you take this from?

**Comment by xenfovn** [comment]
> hi, where did you take this from?

it is the most basic need, many people in discord have asked this

**Comment by JericoFX** [comment]
sorry i didnt express myself correctly, this is taken from ESX? because it look like the code from esx, thats means we need the proper license.

**Comment by BerkieBb** [comment]
We can better just make this a spawnobject function and have a boolean make it networked or not

**Comment by BerkieBb** [comment]
So like this @xenfovn , change the SpawnLocalObject function to this, looks better to me

```lua
QBCore.Functions.SpawnObject = function(model, coords, cb, isnetworked)
    local model = (type(model) == 'number' and model or GetHashKey(model))
    local coords = coords ~= nil and coords or QBCore.Functions.GetCoords(PlayerPedId())
    local isnetworked = isnetworked ~= nil and isnetworked or true

    Citizen.CreateThread(function()
        RequestModel(model)
        while not HasModelLoaded(model) do
            Citizen.Wait(10)
        end

        local obj = CreateObject(model, coords.x, coords.y, coords.z, isnetworked, false, true)
        local netid = NetworkGetNetworkIdFromEntity(obj)

        SetNetworkIdCanMigrate(netid, true)
        SetModelAsNoLongerNeeded(model)

        if cb ~= nil then
            cb(obj)
        end
    end)
end
```

**Pull request closed without merging**
