### PR TITLE
Fixes QBCore.Functions.HasItem [Critical](!)

### PR DESCRIPTION
**Pull request by Mojito-Fivem**
**Describe Pull request**
Fixes QBCore.Functions.HasItem, this function does not work and now it does :)

This PR is very important

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Comment by LifeGoal** [comment]
This does not work when trying to use multiple QBCore.Functions.HasItem. Like if you would need to search for 3 items or whatever.

**Comment by Mojito-Fivem** [comment]
This function is only used to detect the presence of a single item

**Comment by LifeGoal** [comment]
Absolutely, you always check for 1 item. I'm not trying to do something like this
```lua
QBCore.Functions.HasItem("item1", "item2", "item3")
```
or whatever.

What I'm saying is that, it stops working if you try to do something like this:
```lua
local hasItem1 = QBCore.Functions.HasItem("whateverItem1") -- Works for this one
local hasItem2 = QBCore.Functions.HasItem("whateverItem2") -- Here the entire Thread stops (if you are using it inside a thread)
```

**Comment by Mojito-Fivem** [comment]
Have you tried Citizen.Awaiting the result since it returns a promise now

**Comment by LifeGoal** [comment]
> Have you tried Citizen.Awaiting the result since it returns a promise now

That worked :)

**Comment by ItsVinnyX** [comment]
> Absolutely, you always check for 1 item. I'm not trying to do something like this
> 
> ```lua
> QBCore.Functions.HasItem("item1", "item2", "item3")
> ```
> 
> or whatever.
> 
> What I'm saying is that, it stops working if you try to do something like this:
> 
> ```lua
> local hasItem1 = QBCore.Functions.HasItem("whateverItem1") -- Works for this one
> local hasItem2 = QBCore.Functions.HasItem("whateverItem2") -- Here the entire Thread stops (if you are using it inside a thread)
> ```

Having similar issues, I am pretty new to FiveM development. Not sure when await the result.

`if itemOne and itemTwo and (math.random(0, 100) <= 80)) then
                HasKey = true
                QBCore.Functions.Notify("Hotwiring was successful!")
                TriggerEvent("vehiclekeys:client:ToggleEngine")
            else
                HasKey = false
                SetVehicleEngineOn(veh, false, false, true)
                QBCore.Functions.Notify("Hotwire failed!", "error")
            end`

Kills the thread immediately after two items are involved.

**Comment by Mojito-Fivem** [comment]
```
local hasItem1 = Citizen.Await(QBCore.Functions.HasItem("item1"))
```

**Comment by ItsVinnyX** [comment]
image

```lua
local hasItemOne = Citizen.Await(QBCore.Functions.HasItem("advancedlockpick"))
local hasItemTwo = Citizen.Await(QBCore.Functions.HasItem("lockpick"))

            if (hasItemOne and hasItemTwo and (math.random(0, 100) <= 60)) then
                HasKey = true
                QBCore.Functions.Notify("Hotwiring was successful!")
                TriggerEvent("vehiclekeys:client:ToggleEngine")
            else
                HasKey = false
                SetVehicleEngineOn(veh, false, false, true)
                QBCore.Functions.Notify("Hotwire failed!", "error")
            end
```
Not familiar with promise either, doesn't the result return true/false?

**Comment by Mojito-Fivem** [comment]
You can't await it there because the promise has already been resolved

**Comment by LifeGoal** [comment]
> Not familiar with promise either, doesn't the result return true/false?



> You can't await it there because the promise has already been resolved

I think it would be better if you told him where he needs to await it tbh

**Comment by ItsVinnyX** [comment]
Yes! Would help a lot!! As well as be appreciated.

> > You can't await it there because the promise has already been resolved
> 
> I think it would be better if you told him where he needs to await it tbh

**Pull request merged**
