### PR TITLE
tweak(index.html): Fix css/js href

### PR DESCRIPTION
**Pull request by mk3ext**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Comment by FjamZoo** [comment]
😆

Yeah I was wondering mine was messing up aswell

**Comment by jnccloud** [comment]
Still a few missing, I added them all in #556

**Comment by IdrisDose** [comment]
> Still a few missing, I added them all in #556 

Can you update yours and I'll PR it

**Comment by jnccloud** [comment]
> > Still a few missing, I added them all in #556
> 
> Can you update yours and I'll merge it.

Yup done

**Pull request merged**
