### PR TITLE
qb-management exports

### PR DESCRIPTION
**Pull request by ARSSANTO**
**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] 
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by mk3ext — CHANGES_REQUESTED** [review]
The management still creates the functions and callbacks under bossmenu, so this is unneeded
See https://github.com/qbcore-framework/qb-management/blob/main/server/sv_boss.lua#L87

**Review by ItsANoBrainer — APPROVED** [review]
Approved for when qb-management is moved over. 
This approval also requires the export be created.

May be best to have some legacy support check.

**Comment by ItsANoBrainer** [comment]
> The management still creates the functions and callbacks under bossmenu, so this is unneeded See https://github.com/qbcore-framework/qb-management/blob/main/server/sv_boss.lua#L87

What? The resource name is qb-management, not qb-bossmenu, so what you're saying makes no sense.

Also the export isnt' even created in qb-management.

**Comment by ARSSANTO** [comment]
i am using it like that in a good economical player based with society no issues are heard  till now and i deleted boss menu and gang menu

**Comment by GhzGarage** [comment]
#553 same

**Pull request closed without merging**
