### PR TITLE
Items for qb-mechanicjob

### PR DESCRIPTION
**Pull request by Bigbearbeasttv**
added items for repairs using engine parts. need mechanicjob and crafting PRs as well

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by Bigbearbeasttv** [comment]
f. skin command was supposed to be its own PR...oh well

**Comment by BerkieBb** [comment]
> Give Cloothing Menu (Admin Only)
Should be Clothing if my eyes didn't fool me

**Comment by Bigbearbeasttv** [comment]
> > Give Cloothing Menu (Admin Only)
> 
> Should be Clothing if my eyes didn't fool me

You right 😂

**Review by Eralpozcan — APPROVED** [review]

**Comment by IdrisDose** [comment]
Hey bear, when you're free can you update this PR ?

**Comment by Bigbearbeasttv** [comment]
I'm going to close all these and just do a fresh PR

**Pull request closed without merging**
