### PR TITLE
Fixed missing return statement in Player.Functions.HasItem

### PR DESCRIPTION
**Pull request by AdrianCeku**
## Description

`self.Functions.HasItem` calls `QBCore.Functions.HasItem`, but does not return any value due to a missing return statement. 

I added the return statement so the function can be called from the Player Object instead of having to resort to calling `QBCore.Function.HasItem` and passing the source manually
## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Review by Z3rio — APPROVED** [review]
LGTM, hilarious how no one has noticed this previously.

**Comment by AdrianCeku** [comment]
@Z3rio is this gonna be merged? This PR is literally one Word so I dont think it should take too much effort to merge

**Comment by Z3rio** [comment]
> @Z3rio is this gonna be merged? This PR is literally one Word so I dont think it should take too much effort to merge

I believe you might be a bit confused.
I do not have any affiliation with the qbcore organization, nor can I merge PRs.
The only one who can merge PRs would be @GhzGarage

**Comment by AdrianCeku** [comment]
@Z3rio oh im sorry. I just assumed you were a dev form qb-core because but I should have probably checked beforehand 😅. My apologies

**Comment by Cocodrulo** [comment]
I was the one that changed that file with a PR previously, my bad. This PR should be merged.

**Pull request merged**
